# Ivory CKEditor
configs:
    minimal_config:
        extraPlugins: "mediasbrowser"
toolbars:
    items:
        insert:     [ "Mediasbrowser" ]
plugins:
    mediasbrowser:
        path:     "/bundles/minimalimage/js/ckeditor/plugins/mediasbrowser/"
        filename: "plugin.js"
